[package]
name = "ntp-clock"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive", "env"] }
serde = { version = "1.0.228", features = ["derive"] }
time = "0.3.45"
tokio = { version = "1.49.0", features = ["full"] }
hickory-resolver = "0.25.2"
