---
name: Rust Testing
"on":
  push:
  pull_request:
# env:
#   SCCACHE_GHA_ENABLED: "true"
#   RUSTC_WRAPPER: "sccache"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo_test:
    runs-on: macos-latest
    env:
      CARGO_TARGET_THUMBV8M_MAIN_NONE_EABIHF_RUSTFLAGS: "-D warnings -C link-arg=-Tlink.x"
    steps:
      - uses: actions/checkout@v6
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.92.0
          target: thumbv8m.main-none-eabihf
      - uses: extractions/setup-just@v3
      - name: "Download firmware"
        run: ./ntp-clock-hardware/scripts/download-firmware.sh
      - name: "Run tests"
        run: just test
      - name: "Installing tools"
        run: |
          brew install picotool elf2uf2-rs llvm
          echo "/opt/homebrew/opt/llvm/bin" >> "$GITHUB_PATH"
      - name: "Build hardware (verbose)"
        run: cargo build -p ntp-clock-hardware --target thumbv8m.main-none-eabihf --profile release -vv
      - name: "Build the workspace"
        run: |
          picotool version && rustc --version
          FORCE=1 just build
      # - name: Run sccache stat for check
      #   shell: bash
      #   run: ${SCCACHE_PATH} --show-stats
